name: Deploy to VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start SSH agent and add private key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.VM_PRIVATE_KEY }}

    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: "35.194.1.2"
        username: "githubuser"
        key: ${{ secrets.VM_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/oursystemapps/rental_app
          git pull
          npm install
          pm2 restart all || pm2 start server.js
          echo "Deployment done ✔️"
