name: Deploy Frontend & Build Flutter

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Start SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add VM to known_hosts
      run: ssh-keyscan -H 35.194.1.2 >> ~/.ssh/known_hosts

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no oursystemapps@35.194.1.2 "
          cd /home/oursystemapps/rental_app &&
          git pull &&
          echo 'Code pulled at $(date)' &&
          
          # --- Build Flutter Web ---
          flutter clean &&
          flutter pub get &&
          flutter build web --release &&
          
          # --- Deploy to web root ---
          sudo rm -rf /var/www/html/* &&
          sudo cp -r build/web/* /var/www/html/ &&
          
          sudo systemctl restart nginx || true &&
          echo 'Deployment completed at $(date)'
        "
